# Generated by Django 4.1.2 on 2022-10-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('joining_date', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=10)),
            ],
        ),
    ]
